name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-release-tag:
      name: "create release for new tag created"
      runs-on: ubuntu-latest
      steps:
        - name: "create release for new tag created"
          uses: actions/github-script@v6
          id: createRelease
          with:
            script: |
              try{
                const res = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: 'v1.0.9',
                name: 'v1.0.9',
              });
              }catch(error){
                core.setFailed(error.message);
              }
  
  upload-assets:
    needs: create-release-tag
    uses: ./.github/workflows/upload-assets.yml
    with:
      latest-release-tag: 'v1.0.9'
