name: Branch Naming Policy Action

on:
  create:
  delete:
  pull_request:
    branches:
      - main

jobs:
  check-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source
        uses: actions/checkout@v3
          
  branch-naming-policy:
    uses: ./.github/workflows/manage-branch.yml
    with:
      app-name: abcd
    secrets: inherit
