name: Branch Naming Policy Action

on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of  the application'
        required: true
        type: string
     
jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check Code Owner
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            // Get owners from CODEOWNERS
            const fs = require('fs');
            const path = './.github/CODEOWNERS';
            var owners = {};
            await fs.readFileSync(path).toString().split("\n")
              .forEach((el) => {
                if (!el.startsWith("#") && el.trim() != "") {
                  let result = el.trim().split(/\s+/);
                  owners[result[0]] = result.splice(1, result.length).join();
                }
              });
            
            var checkExist = Object.keys(owners).some((name) => name == '${{inputs.app-name}}');
            
            if(!checkExist){
              core.setFailed("app name is N/A")
            }
      
      - name: Run Branch Naming Policy Action
        uses: Ring910/branch-naming@v1
        if: (github.ref_type == 'branch' || github.ref_type == 'pull_request') && success()
        with:
          token: ${{ secrets.REPO_TOKEN }}
          regex: '^${{inputs.app-name}}/(feature|bugfix|hotfix)\/.*'
          app-name: ${{ inputs.app-name }}
