name: Branch Naming Policy

on:
#   create:
#   delete:
  pull_request:
    branches:
      - ref

jobs:
  demosite-branch-naming-policy:
    uses: ./.github/workflows/manage-branch.yml
    with:
      app-name: demosite
    secrets: inherit
  plt-dashboard-branch-naming-policy:
    uses: ./.github/workflows/manage-branch.yml
    with:
      app-name: plt-dashboard
    secrets: inherit
#   plt-web-branch-naming-policy:
#     uses: ./.github/workflows/branch-name-workflow.yml
#     with:
#       app-name: plt-web
#     secrets: inherit
