name: Upload Artifact Release Call

on:
  workflow_call:
    inputs:
      latest-release-tag:
        description: "Tag name of the latest release"
        required: true
        type: string
    
jobs:
  upload-artifacts:
    name: "upload artifacts to release"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v3
          id: download
          with:
            name: test
            path: ./test

        - name: 'Echo download path'
          run: echo ${{steps.download.outputs.download-path}}
          
        - name: "upload artifacts"
          uses: actions/github-script@v6
          with:
            script: |
              let runId = ${{ github.run_id }}
              console.log(runId)
              
              let getWorkflowrun = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: runId
              });
              
              console.log(getWorkflowrun)
              
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: runId
              });

              console.log(allArtifacts)
              
              let getArtifactUrl = getWorkflowrun.data.artifacts_url

              let latestRelease = await github.rest.repos.getLatestRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
              });
            
              let fs = require('fs');
             
              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: latestRelease.data.id,
                name: 'test.zip',
                data: 'test',
                headers:{
                  'content-type': 'application/zip',
                },
                url: latestRelease.data.upload_url
              });
              
              
