name: Upload Artifact Release Call

on:
  workflow_call:
    inputs:
      latest-release-tag:
        description: "Tag name of the latest release"
        required: true
        type: string
    
jobs:
  upload-artifacts:
    name: "upload artifacts to release"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v3
          id: download
          with:
            name: 'test'
            path: ./test

        - name: 'Echo download path'
          run: echo ${{steps.download.outputs.download-path}}
        
        - name: 'Zip folder'
          run: Compress-Archive -Path ./test -Destination test.zip
          
        - name: "upload artifacts"
          uses: actions/github-script@v6
          with:
            script: |
              let latestRelease = await github.rest.repos.getLatestRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
              });
            
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/test.zip`, Buffer.from('./test'));
              console.log(fs);
              
              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: latestRelease.data.id,
                name: 'test.zip',
                file: fs.readFileSync('./test/test.zip'),
                headers:{
                  'content-type': 'application/zip',
                },
                url: latestRelease.data.upload_url
              });
              
              
