name: Upload Artifact Release Run

on:
  workflow_run:
    workflows: [build-run]
    types: [completed]
    
jobs:
  upload-artifacts:
    name: "upload artifacts to release"
    runs-on: ubuntu-latest
    steps:
        - name: "upload artifacts"
          uses: actions/github-script@v6
          with:
            script: |
              let runId = ${{ github.run_id }}
              console.log(runId)
             
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
              });
              
              console.log(context.payload.workflow_run.id)
              console.log(allArtifacts)
              
              let latestRelease = await github.rest.repos.getLatestRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
              });
            
              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: latestRelease.data.id,
                name: 'test.zip',
                data: './test.zip',
                headers:{
                  'content-type': 'application/zip',
                },
                url: latestRelease.data.upload_url
              });
              
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/test.zip`, Buffer.from('./test'));
