name: Upload Artifact Release

on:
  workflow_call:
    inputs:
      latest-release-tag:
        description: "Tag name of the latest release"
        required: true
        type: string
#   workflow_run:
#     workflows: [Create Release]
#     types: [completed]

jobs:
  upload-artifacts:
    name: "upload artifacts to release"
    runs-on: ubuntu-latest
    steps:
      - name: "upload artifacts"
        uses: actions/github-script@v6
        with:
          script: |
            let latestRelease = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            
            console.log(context.payload.workflow_run.id)
            console.log(${{inputs.latest-release-tag}})
            
            let uploadRelease = await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: latestRelease.data.id,
                name: 'test.zip',
                data: './test.zip',
                headers:{
                  'content-type': 'application/zip',
                },
                url: latestRelease.data.upload_url
            });
          
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/test.zip`, Buffer.from('./test.zip'));
